[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
build_flags =
    -D USB_SERIAL_HID
    -D STEAM_INPUT_BRIDGE_PROTOCOL_VERSION=1

[env:teensy40-tests]
extends = env:teensy40
test_framework = unity
test_build_src = yes
build_src_filter =
    +<BridgeProtocol.cpp>
