[platformio]
default_envs = teensy40

[env]
build_flags =
    -D STEAM_INPUT_BRIDGE_PROTOCOL_VERSION=1

[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
monitor_speed = 115200
build_flags =
    ${env.build_flags}
    -D USB_SERIAL_HID
