```
# Parser type
····Selected: Manual
# Parser title
····Steam Input Bridge
# Steam directory
····${steamdirglobal}
# User accounts
····Global
# ROMs directory
····
# Steam collections
····
# Search glob
····${title}/**/@(VALORANT.exe|Lion.exe|LeagueClient.exe)
# Search glob-regex
····null
# Manifests Directory
····C:\Users\mohdfareed\Dev\virtual-mouse\bin\srm
# Amazon Games Path Override
····null
····[ ]: Launch games via Amazon Games
# Epic Manifests Directory Override
····null
····[ ]: Launch games via Epic for online services
# Legendary Path Override
····null
# Legendary installed.json Path Override
····null
····[ ]: Launch games via Legendary for online services
# Galaxy Path Override
····null
····[ ]: Launch games via GOG Galaxy
····[ ]: Parse linked executables from GOG Galaxy
····[ ]: Parse using Registry instead of Galaxy DB
# itch.io AppData Directory Override
····null
# Windows-on-Linux Install Drive Redirect
····null
# Application Types
····Selected: game
····[ ]: Find artwork for installed titles only
# Ubisoft Directory Override
····null
····[ ]: Launch games via UPlay for online services
# XboxGames Directory Override
····null
····[ ]: Launch game as UWP instead of launcher helper
# EA Games Directory Override
····null
····[ ]: Launch games via EA Desktop
# Battle.net.exe Path Override
····null
# Executable
····
····[x]: Follow .lnk or .desktop to destination (Windows and Linux only)
····[x]: Append arguments to executable
# Command line arguments
····
# Executable modifier
····"${exePath}"
# "Start In" directory
····
# Title modifier
····${/:/|${title}|}
# Title from custom variable
····Selected:
····[ ]: Case-insensitive variables
····[ ]: Skip file if variable was not found
# Fuzzy matching
····[x]: Replace diacritic characters
····[x]: Aggressive matching
····[x]: Remove (...) and [...] brackets
# Enable Steam Input
····Selected: 2
# PS4 Template
····Selected: null
# PS5 Template
····Selected: null
# PS5 Dualsense Edge Template
····Selected: null
# Xbox 360 Template
····Selected: null
# Xbox One Template
····Selected: null
# Xbox One Elite Template
····Selected: null
# Switch Joy-Con (Left) Template
····Selected: null
# Switch Joy-Con (Right) Template
····Selected: null
# Switch Pro Template
····Selected: null
# Steam Deck Template
····Selected: null
# Steam Controller Template
····Selected: [object Object]
# Artwork providers
····Selected: sgdb,steamCDN
# Artwork provider search queries
····${title}
# Artwork pool
····${title}
····[ ]: Local backups (DRM takedown protection)
····[ ]: Allow NSFW artwork
····[ ]: Allow joke artwork
# Allowed grid styles
····Selected:
# Allowed hero styles
····Selected:
# Allowed logo styles
····Selected:
# Allowed icon styles
····Selected:
# Allowed animation types
····Selected: animated,static
# Allowed banner dimensions
····Selected:
# Allowed hero dimensions
····Selected:
# Allowed portrait dimensions
····Selected:
# Allowed icon dimensions
····Selected:
# Fallback portrait
····
# Fallback banner
····
# Fallback hero
····
# Fallback logo
····
# Fallback icon
····
# Local portraits glob
····
# Local banners glob
····
# Local heroes glob
····
# Local logos glob
····
# Local icons glob
····
```
